version: '3.8'

services:
    php:
        container_name: php
        build:
            context: ./php
        volumes:
        - ./src:/var/www/app
        networks:
        - laravel

    nginx:
        container_name: webserver
        image: nginx:latest
        ports:
        - "80:80"
        volumes:
        - ./src:/var/www/app
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
        - laravel

    mongo:
        container_name: mongo-db
        image: mongo:latest
        volumes:
        - ./mongodb:/data/db
        networks:
        - laravel
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root

    mysql:
        container_name: mysql-db
        image: mysql:latest
        volumes:
        - ./mysql:/var/lib/mysql
        networks:
        - laravel
        environment:
            MYSQL_ROOT_PASSWORD: root

networks:
  laravel:
    driver: bridge
